(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], app=$('#app'), tokenKey='campushire.token';
let token=localStorage.getItem(tokenKey), data=null, user=null, tab='Overview';
const demos={student:['student@campushire.demo','Student@123'],recruiter:['recruiter@campushire.demo','Recruiter@123'],admin:['admin@campushire.demo','Admin@123']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=s=>`<span class="badge ${String(s).toLowerCase().replaceAll(' ','-')}">${esc(s)}</span>`;
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
async function api(path,opts={}){let r=await fetch('/api'+path,{method:opts.method||'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(opts.body?{body:JSON.stringify(opts.body)}:{})});let j=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Error(j.error||'Request failed');return j}
function loginView(mode='login'){ $('#logout').classList.add('hidden');const registering=mode==='register';app.innerHTML=`<section class="login-wrap"><div class="hero"><p class="eyebrow">FROM CAMPUS TO CAREER</p><h1>Your next opportunity<br>starts <span>here.</span></h1><p class="lead">One trusted workspace for students, recruiters and the placement cell. Clear eligibility. Transparent decisions. No spreadsheet archaeology.</p><div class="pills"><span>✓ Server-side eligibility</span><span>✓ Approval workflow</span><span>✓ Persistent audit trail</span></div></div><form id="login" class="login card"><p class="eyebrow">${registering?'CREATE YOUR ACCOUNT':'DEMO ACCESS'}</p><h2>${registering?'Join CampusHire':'Welcome to CampusHire'}</h2>${registering?`<label>Full name<input name="name" required placeholder="Your full name"></label><label>Account type<select name="role" id="reg-role"><option value="student">Student Applicant</option><option value="recruiter">Company Recruiter</option></select></label><div id="student-fields"><label>Registration number<input name="regNo" required placeholder="e.g. 24BIT1001"></label><label>Department<select name="department"><option>IT</option><option>CSE</option><option>AI&DS</option><option>ECE</option><option>EEE</option><option>Mechanical</option><option>Civil</option></select></label><label>CGPA<input name="cgpa" type="number" min="0" max="10" step="0.01" value="7.5" required></label><label>Graduation year<input name="graduationYear" type="number" min="2026" max="2040" value="2027" required></label><label>Resume URL (optional)<input name="resume" type="url" placeholder="https://..."></label></div>`:''}<label>Email<input name="email" type="email" required value="${registering?'':'student@campushire.demo'}" placeholder="you@example.com"></label><label>Password<input name="password" type="password" required minlength="${registering?'8':'1'}" value="${registering?'':'Student@123'}" placeholder="${registering?'At least 8 characters':''}"></label><button class="btn primary full">${registering?'Create account →':'Sign in to dashboard →'}</button><div class="auth-switch">${registering?'<span class="small muted">Admin accounts can only be provisioned by the platform administrator.</span>':'<span class="small muted">New to CampusHire?</span>'}<button type="button" id="toggle-auth" class="btn ${registering?'ghost':'secondary'}">${registering?'← Back to sign in':'Create a student / recruiter account'}</button></div>${registering?'':`<div class="demo"><b>Quick demo login</b><button type="button" data-demo="student">Student</button><button type="button" data-demo="recruiter">Recruiter</button><button type="button" data-demo="admin">Placement Admin</button></div><p class="small muted">Accounts are saved in the local SQLite database and can sign in again later. New students and recruiters can register here.</p>`}</form></section>`;
 $('#toggle-auth').onclick=()=>loginView(registering?'login':'register');
 const roleSelect=$('#reg-role');roleSelect?.addEventListener('change',()=>{const sf=$('#student-fields');if(sf)sf.classList.toggle('hidden',roleSelect.value!=='student');const reg=$('[name="regNo"]');if(reg)reg.required=roleSelect.value==='student';const cg=$('[name="cgpa"]');if(cg)cg.required=roleSelect.value==='student';const gy=$('[name="graduationYear"]');if(gy)gy.required=roleSelect.value==='student';});
 $('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{let j;if(registering){const body=Object.fromEntries(f.entries());if(body.role!=='student'){delete body.regNo;delete body.department;delete body.cgpa;delete body.graduationYear;delete body.resume;}j=await api('/register',{method:'POST',body})}else{j=await api('/login',{method:'POST',body:{email:f.get('email'),password:f.get('password')}})}token=j.token;localStorage.setItem(tokenKey,token);await loadDashboard()}catch(err){toast(err.message)}};
 $$('[data-demo]').forEach(b=>b.onclick=()=>{$('#login').elements.email.value=demos[b.dataset.demo][0];$('#login').elements.password.value=demos[b.dataset.demo][1]});
}
async function loadDashboard(){try{data=await api('/dashboard');user=data.user;$('#logout').classList.remove('hidden');render()}catch(e){token=null;localStorage.removeItem(tokenKey);loginView();toast(e.message)}}
function shell(title,sub,content){app.innerHTML=`<div class="dash-head"><div><p class="eyebrow">${esc(user.role.toUpperCase())} WORKSPACE</p><h1>${esc(title)}</h1><p class="muted">${esc(sub)}</p></div><div><span class="tag">${esc(user.name)}</span></div></div>${content}`}
function statCards(items){return `<div class="stats">${items.map(([n,l])=>`<div class="stat"><strong>${esc(n)}</strong><span>${esc(l)}</span></div>`).join('')}</div>`}
function tabs(names){return `<nav class="tabs">${names.map(n=>`<button class="${tab===n?'active':''}" data-tab="${esc(n)}">${esc(n)}</button>`).join('')}</nav>`}
function wireTabs(){ $$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()})}
function jobCard(j,student=false){let c=(data.companies||[]).find(x=>x.id===j.companyId)||{};let reasons=[];if(student){if(Number(user.cgpa)<Number(j.minCgpa))reasons.push(`CGPA ${j.minCgpa}+ required`);if(!(j.departments||[]).some(d=>String(d).trim().toLowerCase()===String(user.department||'').trim().toLowerCase()))reasons.push(`Your department (${user.department||'not set'}) is not permitted. Allowed: ${(j.departments||[]).join(', ')}`);if(!String(user.resume||'').trim())reasons.push('Add resume link');let applied=(data.applications||[]).some(a=>a.jobId===j.id&&a.studentId===user.id);return `<article class="item"><div class="row">${badge(j.status)} <span class="small muted">${esc(c.name||'Company')}</span></div><h3>${esc(j.title)}</h3><p>${esc(j.location)} · ${esc(j.type)} · ${esc(j.pay)}</p><p class="small">Minimum CGPA: ${j.minCgpa} · Departments: ${esc(j.departments.join(', '))}</p><p>${esc(j.description)}</p>${reasons.length?`<div class="notice">Not eligible: ${esc(reasons.join(' · '))}</div>`:''}<div class="actions">${applied?'<span class="badge approved">Already applied</span>':`<button class="btn primary" data-apply="${j.id}" ${reasons.length?'disabled title="Ineligible"':''}>Apply now</button>`}</div></article>`}
return `<article class="item"><div class="row">${badge(j.status)} <span class="small muted">${esc(c.name||'Company')}</span></div><h3>${esc(j.title)}</h3><p>${esc(j.location)} · ${esc(j.type)} · ${esc(j.pay)}</p><p class="small">Min CGPA ${j.minCgpa} · ${esc(j.departments.join(', '))}</p><p>${esc(j.description)}</p>${user.role==='recruiter'?`<div class="actions"><button class="btn" data-show-apps="${j.id}">View applicants</button></div>`:''}</article>`}
function render(){if(!data||!user)return loginView();if(user.role==='student')return studentView();if(user.role==='recruiter')return recruiterView();adminView()}
function studentView(){let names=['Overview','Opportunities','My Applications','My Profile'];if(!names.includes(tab))tab='Overview';let apps=data.applications||[],jobs=data.jobs||[];let content=tabs(names);
if(tab==='Overview')content+=statCards([[jobs.length,'Approved openings'],[apps.length,'Applications'],[user.cgpa,'Your CGPA'],[user.department,'Department']])+`<div class="section-title"><h2>Recommended opportunities</h2><button class="btn" data-tab="Opportunities">Browse all</button></div><div class="grid">${jobs.slice(0,2).map(j=>jobCard(j,true)).join('')||'<div class="empty">No approved openings yet.</div>'}</div>`;
if(tab==='Opportunities')content+=`<div class="section-title"><h2>Approved openings</h2><span class="small muted">Eligibility is checked again by the server on submission.</span></div><div class="grid">${jobs.map(j=>jobCard(j,true)).join('')||'<div class="empty">No approved openings.</div>'}</div>`;
if(tab==='My Applications')content+=`<div class="grid">${apps.map(a=>{let j=jobs.find(x=>x.id===a.jobId)||{title:'Role',companyId:''};let c=(data.companies||[]).find(x=>x.id===j.companyId)||{};return `<article class="item"><h3>${esc(j.title)}</h3><p>${esc(c.name||'Company')}</p><p>Status: ${badge(a.status)}</p><p class="small muted">Submitted ${esc(a.createdAt)}</p><p class="small">Pipeline: Applied → Under Review → Shortlisted → Interview → Offered</p></article>`}).join('')||'<div class="empty">You have not applied to any roles yet.</div>'}</div>`;
if(tab==='My Profile')content+=`<form id="profile" class="card"><div class="form-grid">${field('name','Full name',user.name)}${field('regNo','Registration number',user.regNo)}<label class="field">Department<select name="department">${['IT','CSE','AI&DS','ECE','EEE','Mechanical','Civil'].map(x=>`<option ${user.department===x?'selected':''}>${x}</option>`).join('')}</select></label>${field('cgpa','CGPA (0–10)',user.cgpa,'number','0.1')}${field('graduationYear','Graduation year',user.graduationYear,'number','1')}${field('resume','Resume URL',user.resume||'','url')}</div><button class="btn primary">Save profile</button></form>`;
shell('Student dashboard',`Welcome back, ${user.name}. Your next step is one good application.`,content);wireTabs();
$$('[data-apply]').forEach(b=>b.onclick=async()=>{if(b.disabled)return; b.disabled=true; const original=b.textContent; b.textContent='Submitting…'; try{await api('/apply',{method:'POST',body:{jobId:b.dataset.apply}});toast('Application submitted successfully');tab='My Applications';await loadDashboard()}catch(e){toast(e.message);b.disabled=false;b.textContent=original}});
$('#profile')?.addEventListener('submit',async e=>{e.preventDefault();let f=new FormData(e.currentTarget),body=Object.fromEntries(f.entries());try{await api('/profile',{method:'POST',body});toast('Profile saved');await loadDashboard();tab='My Profile';render()}catch(err){toast(err.message)}});
}
function field(name,label,value='',type='text',step=''){return `<label class="field">${label}<input name="${name}" type="${type}" ${step?`step="${step}"`:''} value="${esc(value)}" ${name==='cgpa'?'min="0" max="10"':''}></label>`}
function recruiterView(){let names=['Overview','Company profile','Job postings','Applicants'];if(!names.includes(tab))tab='Overview';let content=tabs(names),jobs=data.jobs||[],apps=data.applications||[],companies=data.companies||[];
if(tab==='Overview')content+=statCards([[companies.length,'Company profiles'],[jobs.length,'Job postings'],[jobs.filter(j=>j.status==='pending').length,'Awaiting approval'],[apps.length,'Applications received']])+`<div class="actions"><button class="btn primary" data-tab="Job postings">＋ Create a job posting</button><button class="btn" data-tab="Company profile">＋ Add company profile</button><button class="btn" data-tab="Applicants">View applicants</button></div><div class="section-title"><h2>Your job postings</h2></div><div class="grid">${jobs.map(j=>jobCard(j)).join('')}</div>`;
if(tab==='Company profile')content+=`<div class="grid">${companies.map(c=>`<article class="item">${badge(c.status)}<h3>${esc(c.name)}</h3><p>${esc(c.industry)}</p><p>${esc(c.description)}</p><p class="small muted">${esc(c.website)}</p></article>`).join('')}</div><hr class="divider"><form id="company-form" class="card"><h2>Create company profile</h2><div class="form-grid">${field('name','Company name')}${field('industry','Industry','Technology')}${field('website','Website','https://','url')}<label class="field fullspan">Description<textarea name="description"></textarea></label></div><button class="btn primary">Submit for approval</button></form>`;
if(tab==='Job postings')content+=`<div class="grid">${jobs.map(j=>jobCard(j)).join('')}</div><hr class="divider"><form id="job-form" class="card"><h2>Create job posting</h2><p class="muted small">Every new posting is pending until the Placement Cell approves it.</p><div class="form-grid"><label class="field">Company<select name="companyId" required>${companies.map(c=>`<option value="${c.id}">${esc(c.name)} (${c.status})</option>`).join('')}</select></label>${field('title','Job title')}${field('location','Location','Vellore / Hybrid')}${field('type','Type','Internship')}${field('pay','Compensation','As per company policy')}${field('minCgpa','Minimum CGPA','7.5','number','0.1')}${field('deadline','Application deadline','2026-12-31','date')}<label class="field">Permitted departments<select name="departments" multiple size="4"><option selected>IT</option><option selected>CSE</option><option>AI&DS</option><option>ECE</option><option>EEE</option><option>Mechanical</option></select><small class="muted">Use Ctrl to select multiple departments.</small></label><label class="field fullspan">Description<textarea name="description"></textarea></label></div><button class="btn primary">Submit posting for approval</button></form>`;
if(tab==='Applicants')content+=applicantTable(apps,jobs,data.students||[]);
shell('Recruiter dashboard','Manage company details, openings and candidate pipelines.',content);wireTabs();
$('#company-form')?.addEventListener('submit',async e=>{e.preventDefault();let body=Object.fromEntries(new FormData(e.currentTarget));try{await api('/company',{method:'POST',body});toast('Company submitted for admin approval');await loadDashboard();tab='Company profile';render()}catch(x){toast(x.message)}});
$('#job-form')?.addEventListener('submit',async e=>{e.preventDefault();let f=new FormData(e.currentTarget),body=Object.fromEntries(f.entries());body.minCgpa=Number(body.minCgpa);body.departments=f.getAll('departments');try{await api('/job',{method:'POST',body});toast('Job submitted for approval');await loadDashboard();tab='Job postings';render()}catch(x){toast(x.message)}});
$$('[data-show-apps]').forEach(b=>b.onclick=()=>{tab='Applicants';render()});
}
function applicantTable(apps,jobs,students){return `<div class="table-wrap"><table><thead><tr><th>Candidate</th><th>Role</th><th>CGPA</th><th>Department</th><th>Status</th><th>Update</th></tr></thead><tbody>${apps.map(a=>{let s=students.find(x=>x.id===a.studentId)||{},j=jobs.find(x=>x.id===a.jobId)||{};return `<tr><td>${esc(s.name||a.studentId)}<br><span class="small muted">${esc(s.regNo||'')}</span></td><td>${esc(j.title||a.jobId)}</td><td>${esc(s.cgpa)}</td><td>${esc(s.department)}</td><td>${badge(a.status)}</td><td><select data-status="${a.id}">${['Applied','Under Review','Shortlisted','Interview','Offered','Rejected'].map(x=>`<option ${a.status===x?'selected':''}>${x}</option>`).join('')}</select></td></tr>`}).join('')}</tbody></table></div><div class="actions"><button class="btn primary" id="batch">Save all status changes</button></div>`}
function adminView(){let names=['Overview','Approvals','Audit log'];if(!names.includes(tab))tab='Overview';let content=tabs(names),co=data.companies||[],jobs=data.jobs||[],audit=data.audit||[];
if(tab==='Overview')content+=statCards([[co.length,'Companies'],[jobs.length,'Job postings'],[co.filter(x=>x.status==='pending').length+jobs.filter(x=>x.status==='pending').length,'Pending approvals'],[audit.length,'Audit events']])+`<div class="notice good">Administrator actions are recorded in the persistent audit log with timestamp, admin ID, action and entity.</div>`;
if(tab==='Approvals'){content+=`<div class="section-title"><h2>Company approvals</h2></div><div class="grid">${co.map(c=>`<article class="item">${badge(c.status)}<h3>${esc(c.name)}</h3><p>${esc(c.industry)} · ${esc(c.description)}</p>${c.status==='pending'?`<div class="actions"><button class="btn primary" data-approve="company:${c.id}:approved">Approve</button><button class="btn" data-approve="company:${c.id}:rejected">Reject</button></div>`:''}</article>`).join('')}</div><div class="section-title"><h2>Job posting approvals</h2></div><div class="grid">${jobs.map(j=>`<article class="item">${badge(j.status)}<h3>${esc(j.title)}</h3><p>${esc((co.find(c=>c.id===j.companyId)||{}).name||'Company')} · CGPA ${j.minCgpa}+ · ${esc(j.departments.join(', '))}</p>${j.status==='pending'?`<div class="actions"><button class="btn primary" data-approve="job:${j.id}:approved">Approve</button><button class="btn" data-approve="job:${j.id}:rejected">Reject</button></div>`:''}</article>`).join('')}</div>`}
if(tab==='Audit log')content+=`<div class="table-wrap"><table><thead><tr><th>Timestamp</th><th>Admin ID</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>${audit.slice().reverse().map(a=>`<tr><td>${esc(a.timestamp)}</td><td>${esc(a.adminId)}</td><td>${esc(a.action)}</td><td>${esc(a.entityType)} / ${esc(a.entityId)}</td><td>${esc(a.details)}</td></tr>`).join('')}</tbody></table></div>`;
shell('Placement Cell Admin','Review submissions, control what goes live and inspect the audit trail.',content);wireTabs();
$$('[data-approve]').forEach(b=>b.onclick=async()=>{let [kind,id,action]=b.dataset.approve.split(':');try{await api(`/admin/${kind}/${id}`,{method:'PATCH',body:{action}});toast(`${kind} ${action}`);await loadDashboard();tab='Approvals';render()}catch(e){toast(e.message)}});
}
document.addEventListener('change',e=>{if(e.target.matches('[data-status]'))e.target.dataset.changed='1'});
document.addEventListener('click',async e=>{if(e.target.id==='batch'){let changed=$$('[data-status][data-changed="1"]');for(let s of changed){try{await api('/application/'+s.dataset.status,{method:'PATCH',body:{status:s.value}})}catch(err){toast(err.message);return}}toast(`Updated ${changed.length} application(s)`);await loadDashboard();tab='Applicants';render()}});
$('#logout').onclick=async()=>{try{await api('/logout',{method:'DELETE'})}catch{}token=null;localStorage.removeItem(tokenKey);data=user=null;tab='Overview';loginView()};
if(token)loadDashboard();else loginView();
})();